### ISSUE TITLE
Coquille - bases de l'astronomie

### ISSUE THREAD

**Issue by jframeau** [AstroAure/Les-bases-detaillees#1]
Capteur – Echantillonnage
La pixel size et la pixel scale doivent être choisies en fonction de la résolution voulue et possible. Ainsi, si le télescope
ne peut rester stable qu’à 5′′-RMS, une pixel scale de moins de 5′′ n’aura pas d’intérêt car les étoiles apparaîtront
comme des traits et non des points **ça** cause du pointage imprécis.

Sinon, merci, super document !

jfr

**Comment by AstroAure** [comment]
Merci de la remarque ! Je viens de corriger la coquille.
